In [1]:
import numpy as np

In [2]:
#Creating first list

a = [[11,12,13], [21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
#Casting list into a 2-D array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
#Number of dimension, axes or rank
A.ndim

2

In [7]:
#Shape of the Numpy Array

A.shape

(3, 3)

In [8]:
# value selection, accessing the 2nd row and 3rd column

A[1,2]

23

In [10]:
#Value Creation, accessing the 3rd row and the 2nd column just using different notation
A[2][1]

32

In [11]:
# 1st role and 1st column

A[0][0]

11

In [13]:
#Slicing the matrix in Numpy, first row and first three column

A[0][0:3]

array([11, 12, 13])

In [16]:
A[0:2][0]

array([11, 12, 13])

In [18]:
A[0:2]

array([[11, 12, 13],
       [21, 22, 23]])

In [17]:
print (A[0:2][0])
print (A[0:2,0])

[11 12 13]
[11 21]


In [19]:
A[0]

array([11, 12, 13])

In [20]:
A[0:2][0][0]

11

In [27]:
#Basic Operations

''' For addition'''


X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])

X+Y

array([[3, 1],
       [1, 3]])

In [24]:
np.add(X,Y)

array([[3, 1],
       [1, 3]])

In [25]:
Z = X+Y

In [26]:
Z

array([[3, 1],
       [1, 3]])

In [28]:
# Multiplying with a Scalar

Z = 2*Y

In [29]:
Z

array([[4, 2],
       [2, 4]])

In [30]:
#Hadamard Product : Each position just multiply themselves only

X

array([[1, 0],
       [0, 1]])

In [31]:
Y

array([[2, 1],
       [1, 2]])

In [32]:
Z = X*Y

In [33]:
Z

array([[2, 0],
       [0, 2]])

In [39]:
# Matrix Mulitiplication of array or dot product

A = np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [45]:
B = np.array([[1,1],[1,1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [47]:
Z = np.dot(A, B)

In [48]:
Z

array([[0, 2],
       [0, 2]])

In [49]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [ ]:
#Getting Transposed Matrix

c=  np.array([[1,1],])